version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    container_name: url-shortener-django
    volumes:
      - .:/app  # Mount the entire project directory
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.base
    depends_on: []