# Generated by Django 4.2.19 on 2025-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('long_url', models.URLField()),
                ('short_code', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
